WITH users AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT 
YEAR(os.SALES_DATE) AS YEAR, 
MONTH(os.SALES_DATE) AS MONTH, 
COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS, 
ROUND(
    COUNT(DISTINCT os.USER_ID) / (SELECT COUNT(*) FROM users)
    , 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS os
JOIN users
ON users.USER_ID = os.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;